#DESIGNED AND DEVELOPED BY ADARSH N
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import webbrowser

grade_points = []
credits = []
total_marks = []
lcdNumber = True


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 650)
        MainWindow.setMinimumSize(QtCore.QSize(740, 650))
        MainWindow.setStyleSheet("background-color: rgb(40, 42, 54);\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 651))
        self.tabWidget.setStyleSheet("background-color: rgb(190, 255, 236);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.sgpa_with_grades = QtWidgets.QWidget()
        self.sgpa_with_grades.setStyleSheet("background-color: rgb(153, 155, 255);")
        self.sgpa_with_grades.setObjectName("sgpa_with_grades")
        self.gridLayoutWidget = QtWidgets.QWidget(self.sgpa_with_grades)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 651, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_19 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout.addWidget(self.comboBox_19, 10, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 2, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout.addWidget(self.comboBox_9, 5, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout.addWidget(self.spinBox_5, 5, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 3, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 3, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout.addWidget(self.spinBox_6, 6, 2, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout.addWidget(self.spinBox_10, 10, 2, 1, 1)
        self.comboBox_21 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.gridLayout.addWidget(self.comboBox_21, 11, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 12, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.comboBox_23 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.gridLayout.addWidget(self.comboBox_23, 12, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout.addWidget(self.spinBox_4, 4, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 2, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout.addWidget(self.spinBox_7, 7, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout.addWidget(self.comboBox_11, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 4, 1, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout.addWidget(self.spinBox_8, 8, 2, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout.addWidget(self.spinBox_9, 9, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 10, 0, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout.addWidget(self.spinBox_12, 12, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout.addWidget(self.comboBox_15, 8, 1, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout.addWidget(self.spinBox_11, 11, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout.addWidget(self.comboBox_13, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.gridLayout.addWidget(self.comboBox_17, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.sgpa_with_grades)
        self.label.setGeometry(QtCore.QRect(10, 0, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_18 = QtWidgets.QLabel(self.sgpa_with_grades)
        self.label_18.setGeometry(QtCore.QRect(30, 470, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lcdNumber = QtWidgets.QLCDNumber(self.sgpa_with_grades)
        self.lcdNumber.setGeometry(QtCore.QRect(440, 470, 131, 41))
        self.lcdNumber.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_19 = QtWidgets.QLabel(self.sgpa_with_grades)
        self.label_19.setGeometry(QtCore.QRect(150, 530, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.sgpa_with_grades)
        self.label_20.setGeometry(QtCore.QRect(210, 580, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton = QtWidgets.QPushButton(self.sgpa_with_grades)
        self.pushButton.setGeometry(QtCore.QRect(150, 430, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.sgpa_with_grades)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 430, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.sgpa_with_grades)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 550, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/adars/.designer/backup/grades.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.sgpa_with_grades, icon, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setStyleSheet("\n"
"background-color: rgb(169, 255, 209);")
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.label_21 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 651, 351))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_37 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_37, 7, 1, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_2.addWidget(self.spinBox_15, 3, 3, 1, 1)
        self.comboBox_29 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_29.setObjectName("comboBox_29")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.comboBox_29.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_29, 3, 1, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout_2.addWidget(self.spinBox_16, 4, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 7, 0, 1, 1)
        self.comboBox_47 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_47.setObjectName("comboBox_47")
        self.comboBox_47.addItem("")
        self.comboBox_47.addItem("")
        self.comboBox_47.addItem("")
        self.comboBox_47.addItem("")
        self.comboBox_47.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_47, 12, 1, 1, 1)
        self.spinBox_24 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_24.setObjectName("spinBox_24")
        self.gridLayout_2.addWidget(self.spinBox_24, 12, 3, 1, 1)
        self.spinBox_18 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridLayout_2.addWidget(self.spinBox_18, 6, 3, 1, 1)
        self.spinBox_20 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_20.setObjectName("spinBox_20")
        self.gridLayout_2.addWidget(self.spinBox_20, 8, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 5, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 10, 0, 1, 1)
        self.comboBox_45 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_45.setObjectName("comboBox_45")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.comboBox_45.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_45, 11, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 1, 1, 1)
        self.comboBox_27 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_27.setObjectName("comboBox_27")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.comboBox_27.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_27, 2, 1, 1, 1)
        self.spinBox_23 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_23.setObjectName("spinBox_23")
        self.gridLayout_2.addWidget(self.spinBox_23, 11, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 4, 0, 1, 1)
        self.comboBox_33 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_33, 5, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 12, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 9, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 11, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 1, 0, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_2.addWidget(self.spinBox_13, 1, 3, 1, 1)
        self.comboBox_25 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_25, 1, 1, 1, 1)
        self.comboBox_41 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_41.setObjectName("comboBox_41")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.comboBox_41.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_41, 9, 1, 1, 1)
        self.spinBox_19 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_19.setObjectName("spinBox_19")
        self.gridLayout_2.addWidget(self.spinBox_19, 7, 3, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_2.addWidget(self.spinBox_14, 2, 3, 1, 1)
        self.comboBox_35 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_35.setObjectName("comboBox_35")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_35, 6, 1, 1, 1)
        self.spinBox_17 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_17.setObjectName("spinBox_17")
        self.gridLayout_2.addWidget(self.spinBox_17, 5, 3, 1, 1)
        self.spinBox_22 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_22.setObjectName("spinBox_22")
        self.gridLayout_2.addWidget(self.spinBox_22, 10, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 8, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 2, 0, 1, 1)
        self.comboBox_43 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_43.setObjectName("comboBox_43")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.comboBox_43.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_43, 10, 1, 1, 1)
        self.comboBox_31 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_31, 4, 1, 1, 1)
        self.spinBox_21 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_21.setObjectName("spinBox_21")
        self.gridLayout_2.addWidget(self.spinBox_21, 9, 3, 1, 1)
        self.comboBox_39 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_39.setObjectName("comboBox_39")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.comboBox_39.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_39, 8, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 6, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_38.setGeometry(QtCore.QRect(30, 480, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tabWidgetPage2)
        self.lcdNumber_2.setGeometry(QtCore.QRect(430, 480, 131, 41))
        self.lcdNumber_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_39 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_39.setGeometry(QtCore.QRect(150, 540, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_40.setGeometry(QtCore.QRect(200, 580, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.pushButton_3 = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 430, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.pushButton_4.setGeometry(QtCore.QRect(370, 430, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 540, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/adars/.designer/backup/marks.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabWidgetPage2, icon1, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SGPA CALCULATOR by ADARSH N"))
        self.comboBox_19.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_19.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_19.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_19.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_19.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "4"))
        self.label_5.setText(_translate("MainWindow", "Credits Assigned:-"))
        self.label_13.setText(_translate("MainWindow", "08"))
        self.label_12.setText(_translate("MainWindow", "07"))
        self.label_10.setText(_translate("MainWindow", "05"))
        self.comboBox_21.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_21.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_21.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_21.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_21.setItemText(4, _translate("MainWindow", "4"))
        self.label_16.setText(_translate("MainWindow", "11"))
        self.label_17.setText(_translate("MainWindow", "12"))
        self.label_14.setText(_translate("MainWindow", "09"))
        self.comboBox_23.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_23.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_23.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_23.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_23.setItemText(4, _translate("MainWindow", "4"))
        self.label_7.setText(_translate("MainWindow", "Grade Points:-"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "4"))
        self.label_9.setText(_translate("MainWindow", "04"))
        self.label_3.setText(_translate("MainWindow", "02"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "4"))
        self.label_15.setText(_translate("MainWindow", "10"))
        self.label_8.setText(_translate("MainWindow", "03"))
        self.comboBox_15.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_15.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_15.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_15.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_15.setItemText(4, _translate("MainWindow", "4"))
        self.label_11.setText(_translate("MainWindow", "06"))
        self.label_4.setText(_translate("MainWindow", "Subject No:-"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "4"))
        self.label_2.setText(_translate("MainWindow", "01"))
        self.comboBox_17.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_17.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_17.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_17.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_17.setItemText(4, _translate("MainWindow", "4"))
        self.label.setText(_translate("MainWindow", "CALCULATE SGPA WITH GRADES:-"))
        self.label_18.setText(_translate("MainWindow", "SEMESTER GRADE POINT AVERAGE:-"))
        self.label_19.setText(_translate("MainWindow", "DESIGNED AND DEVELOPED BY ADARSH N"))
        self.label_20.setText(_translate("MainWindow", "FOR VTU STUDENTS ONLY "))
        self.pushButton.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_2.setText(_translate("MainWindow", "CALCULATE"))
        self.pushButton_5.setText(_translate("MainWindow", "USER MANUL/SOUCE CODE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sgpa_with_grades), _translate("MainWindow", "SGPA WITH GRADES"))
        self.label_21.setText(_translate("MainWindow", "CALCULATE SGPA WITH MARKS:-"))
        self.comboBox_37.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_37.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_37.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_37.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_37.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_29.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_29.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_29.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_29.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_29.setItemText(4, _translate("MainWindow", "4"))
        self.label_32.setText(_translate("MainWindow", "07"))
        self.comboBox_47.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_47.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_47.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_47.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_47.setItemText(4, _translate("MainWindow", "4"))
        self.label_30.setText(_translate("MainWindow", "05"))
        self.label_22.setText(_translate("MainWindow", "Subject No:-"))
        self.label_35.setText(_translate("MainWindow", "10"))
        self.comboBox_45.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_45.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_45.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_45.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_45.setItemText(4, _translate("MainWindow", "4"))
        self.label_23.setText(_translate("MainWindow", "Credits Assigned:-"))
        self.comboBox_27.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_27.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_27.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_27.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_27.setItemText(4, _translate("MainWindow", "4"))
        self.label_29.setText(_translate("MainWindow", "04"))
        self.comboBox_33.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_33.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_33.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_33.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_33.setItemText(4, _translate("MainWindow", "4"))
        self.label_37.setText(_translate("MainWindow", "12"))
        self.label_25.setText(_translate("MainWindow", "Total Marks of Subject:-"))
        self.label_34.setText(_translate("MainWindow", "09"))
        self.label_36.setText(_translate("MainWindow", "11"))
        self.label_26.setText(_translate("MainWindow", "01"))
        self.comboBox_25.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_25.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_25.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_25.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_25.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_41.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_41.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_41.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_41.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_41.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_35.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_35.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_35.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_35.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_35.setItemText(4, _translate("MainWindow", "4"))
        self.label_33.setText(_translate("MainWindow", "08"))
        self.label_28.setText(_translate("MainWindow", "03"))
        self.label_27.setText(_translate("MainWindow", "02"))
        self.comboBox_43.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_43.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_43.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_43.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_43.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_31.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_31.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_31.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_31.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_31.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_39.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_39.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_39.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_39.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_39.setItemText(4, _translate("MainWindow", "4"))
        self.label_31.setText(_translate("MainWindow", "06"))
        self.label_38.setText(_translate("MainWindow", "SEMESTER GRADE POINT AVERAGE:-"))
        self.label_39.setText(_translate("MainWindow", "DESIGNED AND DEVELOPED BY ADARSH N"))
        self.label_40.setText(_translate("MainWindow", "FOR VTU STUDENTS ONLY "))
        self.pushButton_3.setText(_translate("MainWindow", "CLEAR"))
        self.pushButton_4.setText(_translate("MainWindow", "CALCULATE"))
        self.pushButton_6.setText(_translate("MainWindow", "USER MANUL/SOUCE CODE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "SGPA WITH MARKS"))
        self.pushButton_2.clicked.connect(self. calculate_1)
        self.pushButton_4.clicked.connect(self. calculate_2)
        self.pushButton.clicked.connect(self. clear_1)
        self.pushButton_3.clicked.connect(self. clear_2)
        self.pushButton_5.clicked.connect(self. openlink)
        self.pushButton_6.clicked.connect(self. openlink)
    
    def openlink(self):
            webbrowser.open('https://github.com/Adarsh232001/VTU-SGPA-CALCULATOR')

    def clear_1(self):
        self.comboBox.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_7.setCurrentIndex(0)
        self.comboBox_9.setCurrentIndex(0)
        self.comboBox_11.setCurrentIndex(0)
        self.comboBox_13.setCurrentIndex(0)
        self.comboBox_15.setCurrentIndex(0)
        self.comboBox_17.setCurrentIndex(0)
        self.comboBox_19.setCurrentIndex(0)
        self.comboBox_21.setCurrentIndex(0)
        self.comboBox_23.setCurrentIndex(0)
        self.spinBox.setValue(0)
        self.spinBox_2.setValue(0)
        self.spinBox_3.setValue(0)
        self.spinBox_4.setValue(0)
        self.spinBox_5.setValue(0)
        self.spinBox_6.setValue(0)
        self.spinBox_7.setValue(0)
        self.spinBox_8.setValue(0)
        self.spinBox_9.setValue(0)
        self.spinBox_10.setValue(0)
        self.spinBox_11.setValue(0)
        self.spinBox_12.setValue(0)
        grade_points.clear()
        credits.clear()
        total_marks.clear()
        self.lcdNumber.display(0)
    
    def clear_2(self):
            self.spinBox_13.setValue(0)
            self.spinBox_14.setValue(0)
            self.spinBox_15.setValue(0)
            self.spinBox_16.setValue(0)
            self.spinBox_17.setValue(0)
            self.spinBox_18.setValue(0)
            self.spinBox_19.setValue(0)
            self.spinBox_20.setValue(0)
            self.spinBox_21.setValue(0)
            self.spinBox_22.setValue(0)
            self.spinBox_23.setValue(0)
            self.spinBox_24.setValue(0)
            self.comboBox_25.setCurrentIndex(0)
            self.comboBox_27.setCurrentIndex(0)
            self.comboBox_29.setCurrentIndex(0)
            self.comboBox_31.setCurrentIndex(0)
            self.comboBox_33.setCurrentIndex(0)
            self.comboBox_35.setCurrentIndex(0)
            self.comboBox_37.setCurrentIndex(0)
            self.comboBox_39.setCurrentIndex(0)
            self.comboBox_41.setCurrentIndex(0)
            self.comboBox_43.setCurrentIndex(0)
            self.comboBox_45.setCurrentIndex(0)
            self.comboBox_47.setCurrentIndex(0)
            grade_points.clear()
            credits.clear()
            total_marks.clear()
            self.lcdNumber_2.display(0)


    def calculate_2(self):
            lcdNumber = False
            credits_0 = int(self.comboBox_25.currentText())
            credits.append(credits_0)
            credits_1 = int(self.comboBox_27.currentText())
            credits.append(credits_1)
            credits_2 = int(self.comboBox_29.currentText())
            credits.append(credits_2)
            credits_3 = int(self.comboBox_31.currentText())
            credits.append(credits_3)
            credits_4 = int(self.comboBox_33.currentText())
            credits.append(credits_4)
            credits_5 = int(self.comboBox_35.currentText())
            credits.append(credits_5)
            credits_6 = int(self.comboBox_37.currentText())
            credits.append(credits_6)
            credits_7 = int(self.comboBox_39.currentText())
            credits.append(credits_7)
            credits_8 = int(self.comboBox_41.currentText())
            credits.append(credits_8)
            credits_9 = int(self.comboBox_43.currentText())
            credits.append(credits_9)
            credits_10 = int(self.comboBox_45.currentText())
            credits.append(credits_10)
            credits_11 = int(self.comboBox_47.currentText())
            credits.append(credits_11)
            marks_0 = self.spinBox_13.value()
            total_marks.append(marks_0)
            marks_1 = self.spinBox_14.value()
            total_marks.append(marks_1)
            marks_2 = self.spinBox_15.value()
            total_marks.append(marks_2)
            marks_3 = self.spinBox_16.value()
            total_marks.append(marks_3)
            marks_4 = self.spinBox_17.value()
            total_marks.append(marks_4)
            marks_5 = self.spinBox_18.value()
            total_marks.append(marks_5)
            marks_6 = self.spinBox_19.value()
            total_marks.append(marks_6)
            marks_7 = self.spinBox_20.value()
            total_marks.append(marks_7)
            marks_8 = self.spinBox_21.value()
            total_marks.append(marks_8)
            marks_9 = self.spinBox_22.value()
            total_marks.append(marks_9)
            marks_10 = self.spinBox_23.value()
            total_marks.append(marks_10)
            marks_11 = self.spinBox_24.value()
            total_marks.append(marks_11)
            marks_to_grades()
            calculate_with_grades(self, lcdNumber)

    def calculate_1(self):
            credits_0 = int(self.comboBox.currentText())
            credits.append(credits_0)
            credits_1 = int(self.comboBox_3.currentText())
            credits.append(credits_1)
            credits_2 = int(self.comboBox_5.currentText())
            credits.append(credits_2)
            credits_3 = int(self.comboBox_7.currentText())
            credits.append(credits_3)
            credits_4 = int(self.comboBox_9.currentText())
            credits.append(credits_4)
            credits_5 = int(self.comboBox_11.currentText())
            credits.append(credits_5)
            credits_6 = int(self.comboBox_13.currentText())
            credits.append(credits_6)
            credits_7 = int(self.comboBox_15.currentText())
            credits.append(credits_7)
            credits_8 = int(self.comboBox_17.currentText())
            credits.append(credits_8)
            credits_9 = int(self.comboBox_19.currentText())
            credits.append(credits_9)
            credits_10 = int(self.comboBox_21.currentText())
            credits.append(credits_10)
            credits_11 = int(self.comboBox_23.currentText())
            credits.append(credits_11)
            grade_0 = self.spinBox.value()
            check_grade(self, grade_0)
            grade_points.append(grade_0)
            grade_1 = self.spinBox_2.value()
            check_grade(self, grade_1)
            grade_points.append(grade_1)
            grade_2 = self.spinBox_3.value()
            check_grade(self, grade_2)
            grade_points.append(grade_2)
            grade_3 = self.spinBox_4.value()
            check_grade(self, grade_3)
            grade_points.append(grade_3)
            grade_4 = self.spinBox_5.value()
            check_grade(self, grade_4)
            grade_points.append(grade_4)
            grade_5 = self.spinBox_6.value()
            check_grade(self, grade_5)
            grade_points.append(grade_5)
            grade_6 = self.spinBox_7.value()
            check_grade(self, grade_6)
            grade_points.append(grade_6)
            grade_7 = self.spinBox_8.value()
            check_grade(self, grade_7)
            grade_points.append(grade_7)
            grade_8 = self.spinBox_9.value()
            check_grade(self, grade_8)
            grade_points.append(grade_8)
            grade_9 = self.spinBox_10.value()
            check_grade(self, grade_9)
            grade_points.append(grade_9)
            grade_10 = self.spinBox_11.value()
            check_grade(self, grade_10)
            grade_points.append(grade_10)
            grade_11 = self.spinBox_12.value()
            check_grade(self, grade_11)
            grade_points.append(grade_11)
            calculate_with_grades(self, lcdNumber)

def calculate_with_grades(self, lcdNumber):
    sum_sgpa = 0
    sum_of_credits = sum(credits)
    try:
        for i in range(len(grade_points)):
                sum_sgpa = sum_sgpa + (credits[i] * grade_points[i])
        final_sgpa = sum_sgpa/sum_of_credits
        if lcdNumber is True:
                self.lcdNumber.display(final_sgpa)
        elif lcdNumber is False:
                self.lcdNumber_2.display(final_sgpa)
        credits.clear()
        grade_points.clear()
    except ZeroDivisionError:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                msg.setText("Enter a the values")
                msg.setInformativeText('More information')
                msg.setWindowTitle("Error")
                msg.exec_()

def check_grade(self, grade):
    if(grade!=0):
        if(grade<11):
                print(grade)
        else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Critical)
                msg.setText("Enter a valid Grades ")
                msg.setInformativeText('More information')
                msg.setWindowTitle("Error")
                msg.exec_()
                

def marks_to_grades():
        for marks in total_marks:
                if(marks>=90):
                        grade_points.append(10)
                elif(marks<90 and marks>=80):
                         grade_points.append(9)
                elif(marks<80 and marks>=70):
                        grade_points.append(8)
                elif(marks<70 and marks>=60):
                        grade_points.append(7)
                elif(marks<60 and marks>=45):
                        grade_points.append(6)
                elif(marks<45 and marks>=40):
                        grade_points.append(4)
                elif(marks<40):
                        grade_points.append(0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
